---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: godemo
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: godemo
    spec:
      volumes:
      - name: localtime
        hostPath:
          path: /etc/localtime
      - name: timezone
        hostPath:
          path: /etc/timezone
      containers:
      - name: godemo
        # 当新版本发布，必须保证这里的版本与VERSION文件一致
        image: k8s-registry:5000/cookeem/godemo:0.1.14
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
        resources:
          limits:
            memory: "256Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: godemo
  labels:
    app: godemo
spec:
  type: NodePort
  selector:
    app: godemo
  ports:
  - name: port-8081
    port: 8081
    targetPort: 8081
    nodePort: 30120
